<?php
/*
 * Implementation of hook_install
 *
 * we are removing the default theme as we set that in code
 * we also enable the datapublic_theme so it can become default
 */

/**
 * Implementation of hook_form_FORM_ID_alter().
 * Alter the installation form to set Canada as the default country.
 */
function datapublic_defaults_form_install_configure_form_alter(&$form, $form_state) {
  $form['server_settings']['site_default_country']['#default_value'] = 'Canada';
}